apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: konflux
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: konflux
    app.kubernetes.io/part-of: konflux
  name: konflux
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: konflux
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: konflux
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/lixiang-happy-tenant/konflux/konflux@sha256:8e07381db7d628a60f3b09a8bd64dbb51e4321bc1b8b6510cf95b349c271a43b
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
