apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: konflux
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: konflux
    app.kubernetes.io/part-of: konflux
  name: konflux
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: konflux
status:
  loadBalancer: {}
